### ISSUE TITLE
Windows 7 - Add Command Issue

### ISSUE THREAD

**Issue by Hashnoob** [Francesco149/weebp#1]
Hey Francesco,

OS: WIN7

I'm having an issue with the command "add" when I use it with or without parameters, it just makes the class/window of choice disappear from the taskbar and view, but it keeps the process running in the background. The command worked twice out of around 50+ tries, it seems very random.

Any thoughts or solutions?

Also thank you for you work on this app I have been looking for an opensource wallpaper engine for a very long time! Although you may want to consider giving this awesome app a more defined name for it's intended purpose it could be easy to overlook, just an idea. :)

**Comment by Hashnoob** [comment]
Workaround: Kill and restart explorer.exe, then setting a new desktop process background works most of the time on Windows 7.

**Comment by Francesco149** [comment]
when you add the window and it fails, does it say just "W: couldn't spawn WorkerW window, trying old method" or also "W: couldnt spawn window behind icons, falling back to Progman" ? also, do you have aero enabled? if not, try enabling it. windows 7 support is very untested, maybe I'll spin up a win7 virtual machine and see if i can reproduce the issue.

**Comment by Hashnoob** [comment]
Hey thanks for the reply!

So I was getting the two errors you mentioned. But I figured out that the explorer.exe had to be restarted. Then I only get one of the errors which is "W: couldn't spawn WorkerW window, trying old method". But the process does get applied successfully below the icons.

And yes Aero was enabled before I tried to initiate every command.

If you want me to try out any other ideas let me know!

**Comment by Hashnoob** [comment]
Commands used.
__
wp run mpv ^
--player-operation-mode=pseudo-gui ^
--force-window=yes ^
--terminal=no ^
--no-audio ^
--loop=inf ^
video.mp4

wp add -t -c mpv -f

**Comment by Hashnoob** [comment]
To run the command again, successfully.
Kill the restart explorer.exe  > run commands

If you don't restart explorer: Running the commands will make the class/window of choice disappear from the taskbar and view, but it keeps the process running in the background.
Output: [0048061A]                                      mpv |   26,  -11, 1894, 1069 | video.mp4 - mpv

If you do restart explorer: It does the same thing as above but also works as intended. But it will come with an additional error.
Output: [00171DC6]                                      mpv |   26,  -11, 1894, 1069 | video.mp4 - mpv
Output: W: couldn't spawn WorkerW window, trying old method

Hope that helps.

**Comment by AClon314** [comment]
@Francesco149 
I have this same problem! The window can't be hidden below the icons. It can't work in the correct way!
But all in all, thanks your open source. I am so looking forward to useing it in the future versions!
**Using Windows 7**
(I M A English Learner,maybe there's some grammar mistakes)

**Comment by AClon314** [comment]
@Hashnoob @Francesco149 It's solved!
![image](http://ws4.sinaimg.cn/large/8f8ff1c9gy1fwn153xegrj20dv0irjt4.jpg)
Just check at least these options(Chinese, the same position as English)
Just like the DreamScene !!!

**Comment by Francesco149** [comment]
@Hashnoob can you retest with 0.6.0 ? I think that might've been an issue with the --fullscreen option not working correctly on multiple monitors and just placing the window out of bounds

as for the visual settings, I'm currently investigating exactly which ones are actually needed to make weebp work

**Comment by Francesco149** [comment]
ok so i investigated this a bit more

it seems that unchecking"Animate controls and elements inside windows" makes it fall back to Progman (not behind icons). so at least that is required. I haven't figured out why it still won't properly capture the window yet though. investigating further...

**Comment by Francesco149** [comment]
figured it out! on newer windows 7 updates it seems that the windows 10 window message works, which means that it tries to use the windows 10 method and doesn't hide the desktop window.

by detecting windows 7 in a more reliable way and hiding the desktop window it works

![](https://i.imgur.com/365SX8I.png)

will push an update soon

**Comment by Francesco149** [comment]
version 0.6.1 fixes this problem, have fun!

**Comment by Hashnoob** [comment]
Got around to checking github again. Your fix is working like a charm, thank you!
