### ISSUE TITLE
dll contains no exported functions?

### ISSUE THREAD

**Issue by phanirithvij** [Francesco149/weebp#13]
I did 

```cmd
dumpbin /exports weebp.dll
```
Which gives this
```
Microsoft (R) COFF/PE Dumper Version 14.24.28314.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file weebp.dll

File Type: DLL

  Summary

        2000 .data
        1000 .pdata
        9000 .rdata
        1000 .reloc
        B000 .text
```
But Ideally it should show the names of the exported functions accroding to [this](https://stackoverflow.com/a/6634722/8608146).

You have implemented the exporting functionality but they didn't export I guess or I'm doing something wrong.
I built the `dll` using the `build.bat` and I'm using `Microsoft Visual Studio 2019`.
No luck. The dump is still the same.

**Comment by phanirithvij** [comment]
[test.zip](https://github.com/Francesco149/weebp/files/4027856/test.zip)
This is a simple dll export code that successfully exports the function in it.

**Comment by phanirithvij** [comment]
It's because `-DWP_IMPLEMENTATION` is missing in the build script. Please add it.

https://github.com/Francesco149/weebp/blob/02a247969baaea9b646ddae6e9080f5da098af05/src/build.bat#L23

**Comment by Francesco149** [comment]
ah yeah i never tested the dll version, i'll add it but i can't test it atm

**Comment by phanirithvij** [comment]
@Francesco149 do you mind sharing the live wallpaper that you showed as an example in the readme. No luck with reverse image search. I mean this [image](https://user-images.githubusercontent.com/29627898/72010079-359cf100-327d-11ea-8255-41396f2b2ce8.png)
