### ISSUE TITLE
License please

### ISSUE THREAD

**Issue by nlhnt** [Francesco149/weebp#16]
License this under GPL or something... People will just still it and release things like that on steam.

Not saying they did.

**Comment by Francesco149** [comment]
the code is still here and open-source. anyone who cares about free software will find it even if proprietary clones are made.

I don't like the restrictions in the GPL license, I lean towards public domain

**Comment by Francesco149** [comment]
closing this, if you want to hear more about the kinds of headaches non-permissive licenses cause and how they, in my opinion, don't actually help open source much, see this part of landley's toybox talk https://youtu.be/MkJkyMuBm3g?t=310
