### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by p4rkrs** [Francesco149/weebp#7]
As a regular Linux user, it would be nice to have software like this on Linux. Because as far as I know, no software (still maintained now) is available on Linux.

**Comment by Francesco149** [comment]
you don't need fancy software to do this on linux, just run ```mpv --wid 0 video.mp4``` if you don't use a compositor, or if you do use a compositor you can install xwinwrap and use that.

the reason i made weebp is that windows didn't have simple command line tools like xwinwrap and you need some trickery to draw behind the desktop icons

**Comment by p4rkrs** [comment]
I see, thanks for the tips! Keep working, I like your project
